### ISSUE TITLE
That could be cool if it support local storage

### ISSUE THREAD

**Issue by jsvisa** [Gisto/Gisto#166] opened 2015-05-21 14:08 UTC
I can't use this APP if I'm offline, if it support local storage, I can create or search some code snippents in local, not in cloud. I think this feature could make me exciting, if you want it too.

**Comment by sanusart** [comment] 2015-05-21 14:35
Please refere to #5

**Comment by sanusart** [comment] 2017-10-31 07:59
closing as duplicate of #5

**Closed by sanusart** 2017-10-31 07:59 UTC
